const productsData = [
  {
    name: "S!¡ᔑᓵᒷ bꖎᔑᓭℸ ̣ ᒷ∷ 700",
    price: 2355.99,
    imageUrl: "/images/gun1.jpg",
    description: "Nᔑᒲ ᔑℸ ̣ ᑑ⚍ᒷ ᑑ⚍𝙹ᓭ ╎↸ ᓭᒷᑑ⚍╎ リᒷᓭᓵ╎⚍リℸ",
    popular: true,
  },
  {
    name: "S!¡ᔑᓵᒷᓭ⍑╎!¡ 𝙹╎ꖎ",
    price: 76.44,
    imageUrl: "/images/goo.png",
    description: "Wᒷ ᔑ∷ᒷ ᓭ⚍∷ᒷ ℸ ̣ ⍑ᔑℸ ̣  𝙹リᒷ ∴ᔑ∷ ╎ᓭ ᒷリ𝙹⚍⊣⍑.",
    popular: true,
  },
  {
    name: "E||ᒷ ᓭᓵ∷ᒷᔑᒲ ╎ᓵᒷ ᓵ∷ᒷᔑᒲ",
    price: 19.99,
    imageUrl: "/images/ice.png",
    description: "T⍑ᒷ ʖ╎∷ᓵ⍑ ꖎ𝙹𝙹ꖌᒷ↸ ᓭℸ ̣ ᔑ∷ꖌ ∴⍑╎ℸ ̣ ᒷ ᔑリ↸ ꖎ𝙹リ",
    popular: false,
  },
  {
    name: "E ̇/ᓵᔑ⍊ᔑℸ ̣ 𝙹∷",
    price: 3458.89,
    imageUrl: "/images/exca.jpg",
    description: "Tᔑꖌᒷ ℸ ̣ ∴𝙹 ᓭ⍑ᔑ∷ᒷᓭ ᔑᓭ ᔑ ⎓ᔑ╎∷ !¡∷𝙹⎓╎ℸ ̣.",
    popular: false,
  },
  {
    name: "L╎⊣⍑ℸ ̣ ᓭᔑʖᒷ∷",
    price: 12459.65,
    imageUrl: "/images/saber.png",
    description: "Cᔑ!¡ ℸ ̣ ⍑ᒷ ⋮ᔑ∷ ∴╎ℸ ̣ ⍑ ᔑ ℸ ̣ ╎⊣⍑ℸ ̣  ʖ∷ᔑᓭᓭ ᓵ𝙹⍊ᒷ∷. ",
    popular: true,
  },
  {
    name: "R╎⊣⍑ℸ ̣ ∴╎リ⊣",
    price: 3887.87,
    imageUrl: "/images/part1.png",
    description: "S⍑ᒷ ᓭᔑ∴ ᔑ ᓵᔑℸ ̣  ╎リ ℸ ̣ ⍑ᒷ リᒷ╎⊣⍑ʖ𝙹∷'ᓭ ⍑𝙹⚍ᓭᒷ. ",
    popular: false,
  },
  {
    name: "W╎リ⊣ᒷ↸ ⎓ᒷ∷∷ᒷℸ ̣  07",
    price: 54837.78,
    imageUrl: "/images/ship2.jpg",
    description: "Sᒷᒷ ℸ ̣ ⍑ᒷ !¡ꖎᔑ||ᒷ∷ ᓭᓵ𝙹𝙹ℸ ̣  ℸ ̣ 𝙹 ℸ ̣ ⍑╎∷↸ ʖᔑᓭᒷ. T⍑ᒷ ",
    popular: false,
  },
  {
    name: "S!¡╎ꖌ||⎓∷⚍╎ℸ ̣",
    price: 1.56,
    imageUrl: "/images/fruit.jpg",
    description: "T⍑ᒷ nᔑ⍊|| ᔑℸ ̣ ℸ ̣ ᔑᓵꖌᒷ↸ ℸ ̣ ⍑ᒷ ʖ╎⊣ ℸ ̣ ᔑᓭꖌ ⎓𝙹∷ᓵᒷ. ",
    popular: true,
  },
  {
    name: "C𝙹∴",
    price: 156.78,
    imageUrl: "/images/cow.jpg",
    description: "T⍑ᒷ ⎓∷⚍╎ℸ ̣  !¡ᒷᒷꖎ ∴ᔑᓭ ᓵ⚍ℸ ̣  ╎リ ℸ ̣ ⍑╎ᓵꖌ ᓭꖎ╎ᓵᒷᓭ.",
    popular: true,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
  {
    name: "",
    price: 0,
    imageUrl: "/images/",
    description: "",
    popular: false,
  },
];

module.exports = productsData;
